/** Client-side fallbacks when public plan APIs fail or are slow (Hostinger cold start). */
import type { InvestmentPlan } from "@workspace/api-client-react";
import type { StakingPlan } from "@/lib/staking-api";

export const FALLBACK_INVESTMENT_PLANS: InvestmentPlan[] = [
  {
    id: -1,
    name: "Starter Plan",
    description: "Perfect for new investors. Low risk, steady returns.",
    minAmount: 500,
    maxAmount: 5000,
    roiPercent: 8.5,
    durationDays: 30,
    currency: "USD",
    isActive: true,
    totalInvestors: 1247,
    category: "starter",
    planType: "monthly",
    profitFrequency: "monthly",
    capitalReturn: "yes",
    autoRenewal: false,
    earlyWithdrawalPenalty: 0,
    features: [],
    maxInvestors: null,
    createdAt: null,
  },
  {
    id: -2,
    name: "Growth Plan",
    description: "Balanced portfolio for consistent wealth growth.",
    minAmount: 5000,
    maxAmount: 25000,
    roiPercent: 15,
    durationDays: 60,
    currency: "USD",
    isActive: true,
    totalInvestors: 834,
    category: "growth",
    planType: "monthly",
    profitFrequency: "monthly",
    capitalReturn: "yes",
    autoRenewal: false,
    earlyWithdrawalPenalty: 0,
    features: [],
    maxInvestors: null,
    createdAt: null,
  },
  {
    id: -3,
    name: "Premium Plan",
    description: "Advanced strategies for seasoned investors.",
    minAmount: 25000,
    maxAmount: 100000,
    roiPercent: 24,
    durationDays: 90,
    currency: "USD",
    isActive: true,
    totalInvestors: 312,
    category: "premium",
    planType: "monthly",
    profitFrequency: "monthly",
    capitalReturn: "yes",
    autoRenewal: false,
    earlyWithdrawalPenalty: 0,
    features: [],
    maxInvestors: null,
    createdAt: null,
  },
  {
    id: -4,
    name: "Elite Plan",
    description: "Exclusive hedge fund strategies. Maximum returns.",
    minAmount: 100000,
    maxAmount: 1000000,
    roiPercent: 36,
    durationDays: 180,
    currency: "USD",
    isActive: true,
    totalInvestors: 89,
    category: "elite",
    planType: "monthly",
    profitFrequency: "monthly",
    capitalReturn: "yes",
    autoRenewal: false,
    earlyWithdrawalPenalty: 0,
    features: [],
    maxInvestors: null,
    createdAt: null,
  },
];

export const FALLBACK_STAKING_PLANS: StakingPlan[] = [
  {
    id: -1,
    name: "Flexible Staking",
    description: "Stake anytime, withdraw with minimal lock.",
    planType: "flexible",
    currency: "USDT",
    minAmount: 100,
    maxAmount: 50000,
    aprPercent: 8,
    apyPercent: 8.3,
    roiPercent: 8,
    lockDurationDays: 0,
    isFlexible: true,
    rewardFrequency: "daily",
    compoundEnabled: true,
    autoRenew: false,
    earlyWithdrawalPenalty: 0,
    promotionalBonusPercent: 0,
    isFeatured: false,
    isPopular: true,
    isRecommended: false,
    riskLevel: "low",
    themeColor: "#22c55e",
    iconKey: "coins",
    totalStaked: 0,
    activeStakers: 0,
  },
  {
    id: -2,
    name: "30-Day Lock",
    description: "Higher yield with a 30-day commitment.",
    planType: "fixed",
    currency: "USDT",
    minAmount: 500,
    maxAmount: 100000,
    aprPercent: 12,
    apyPercent: 12.7,
    roiPercent: 12,
    lockDurationDays: 30,
    isFlexible: false,
    rewardFrequency: "daily",
    compoundEnabled: true,
    autoRenew: true,
    earlyWithdrawalPenalty: 2,
    promotionalBonusPercent: 0,
    isFeatured: true,
    isPopular: false,
    isRecommended: true,
    riskLevel: "medium",
    themeColor: "#f59e0b",
    iconKey: "lock",
    totalStaked: 0,
    activeStakers: 0,
  },
  {
    id: -3,
    name: "90-Day Premium",
    description: "Premium tier for long-term stakers.",
    planType: "fixed",
    currency: "USDT",
    minAmount: 1000,
    maxAmount: 250000,
    aprPercent: 18,
    apyPercent: 19.6,
    roiPercent: 18,
    lockDurationDays: 90,
    isFlexible: false,
    rewardFrequency: "daily",
    compoundEnabled: true,
    autoRenew: true,
    earlyWithdrawalPenalty: 5,
    promotionalBonusPercent: 0,
    isFeatured: false,
    isPopular: false,
    isRecommended: false,
    riskLevel: "medium",
    themeColor: "#a855f7",
    iconKey: "gem",
    totalStaked: 0,
    activeStakers: 0,
  },
  {
    id: -4,
    name: "180-Day Elite",
    description: "Maximum rewards for committed investors.",
    planType: "fixed",
    currency: "USDT",
    minAmount: 5000,
    maxAmount: 500000,
    aprPercent: 24,
    apyPercent: 27.1,
    roiPercent: 24,
    lockDurationDays: 180,
    isFlexible: false,
    rewardFrequency: "daily",
    compoundEnabled: true,
    autoRenew: true,
    earlyWithdrawalPenalty: 8,
    promotionalBonusPercent: 0,
    isFeatured: false,
    isPopular: false,
    isRecommended: false,
    riskLevel: "high",
    themeColor: "#ef4444",
    iconKey: "crown",
    totalStaked: 0,
    activeStakers: 0,
  },
];
