/** Sample algo strategies with monthly / quarterly / half-yearly / annual subscription pricing. */
export const SAMPLE_ALGO_STRATEGIES = [
  {
    name: "Quantum Momentum",
    description: "Multi-asset momentum engine using volatility-adjusted position sizing across forex majors and gold.",
    roi: "22.4",
    riskLevel: "medium" as const,
    status: "active" as const,
    subscribers: 142,
    minInvestment: "500",
    currency: "USD",
    priceMonthly: "79",
    priceQuarterly: "199",
    priceBiannual: "359",
    priceAnnual: "619",
  },
  {
    name: "Alpha Arbitrage",
    description: "Low-latency statistical arbitrage across correlated pairs with strict drawdown controls.",
    roi: "14.8",
    riskLevel: "low" as const,
    status: "active" as const,
    subscribers: 98,
    minInvestment: "250",
    currency: "USD",
    priceMonthly: "59",
    priceQuarterly: "149",
    priceBiannual: "269",
    priceAnnual: "459",
  },
  {
    name: "Gold Pulse AI",
    description: "XAUUSD-focused neural signal stack with session filters and news blackout windows.",
    roi: "31.2",
    riskLevel: "high" as const,
    status: "active" as const,
    subscribers: 211,
    minInvestment: "1000",
    currency: "USD",
    priceMonthly: "99",
    priceQuarterly: "259",
    priceBiannual: "459",
    priceAnnual: "799",
  },
  {
    name: "FX Neural Net",
    description: "Deep-learning trend classifier on EUR/USD, GBP/USD and USD/JPY with adaptive stop placement.",
    roi: "19.6",
    riskLevel: "medium" as const,
    status: "active" as const,
    subscribers: 167,
    minInvestment: "500",
    currency: "USD",
    priceMonthly: "69",
    priceQuarterly: "179",
    priceBiannual: "319",
    priceAnnual: "549",
  },
  {
    name: "Crypto Wave Rider",
    description: "BTC and ETH swing system using on-chain volume spikes and funding-rate confirmation.",
    roi: "28.5",
    riskLevel: "high" as const,
    status: "active" as const,
    subscribers: 189,
    minInvestment: "750",
    currency: "USD",
    priceMonthly: "89",
    priceQuarterly: "229",
    priceBiannual: "409",
    priceAnnual: "699",
  },
  {
    name: "Index Momentum Pro",
    description: "US30 and NAS100 breakout model with earnings-season risk throttling and gap filters.",
    roi: "17.3",
    riskLevel: "medium" as const,
    status: "active" as const,
    subscribers: 124,
    minInvestment: "500",
    currency: "USD",
    priceMonthly: "75",
    priceQuarterly: "189",
    priceBiannual: "339",
    priceAnnual: "579",
  },
  {
    name: "Mean Reversion Bot",
    description: "Range-bound mean reversion on low-volatility pairs during Asian and London sessions.",
    roi: "12.1",
    riskLevel: "low" as const,
    status: "active" as const,
    subscribers: 76,
    minInvestment: "300",
    currency: "USD",
    priceMonthly: "49",
    priceQuarterly: "129",
    priceBiannual: "229",
    priceAnnual: "399",
  },
  {
    name: "Volatility Breakout",
    description: "ATR expansion breakout system for high-volatility crosses with trailing profit locks.",
    roi: "25.8",
    riskLevel: "high" as const,
    status: "active" as const,
    subscribers: 153,
    minInvestment: "800",
    currency: "USD",
    priceMonthly: "85",
    priceQuarterly: "219",
    priceBiannual: "389",
    priceAnnual: "669",
  },
];
