import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import investmentsRouter from "./investments";
import tradesRouter from "./trades";
import algoStrategiesRouter from "./algoStrategies";
import copyTradingRouter from "./copyTrading";
import eaStrategiesRouter from "./eaStrategies";
import transactionsRouter from "./transactions";
import adminRouter from "./admin";
import adminNotificationsRouter from "./adminNotifications";
import superAdminRouter from "./superAdmin";
import plansRouter from "./plans";
import kycRouter from "./kyc";
import referralRouter from "./referral";
import mt5Router from "./mt5";
import mt5RelayRouter from "./mt5Relay";
import ticketsRouter from "./tickets";
import notificationsRouter from "./notifications";
import walletRouter from "./wallet";
import managerRouter from "./manager";
import supportTeamRouter from "./supportTeam";
import supportMailRouter from "./supportMail";
import promoterRouter from "./promoter";
import twoFactorRouter from "./twoFactor";
import roiEngineRouter from "./roiEngine";
import auditLogsRouter from "./auditLogs";
import promoCodesRouter from "./promoCodes";
import agreementsRouter from "./agreements";
import paymentsRouter from "./payments/index";
import walletLedgerRouter from "./walletLedger";
import paymentAccountsRouter from "./paymentAccounts";
import onboardingRouter from "./onboarding";
import brandingRouter from "./branding";
import marketRouter from "./market";
import uploadsRouter from "./uploads";

const router: IRouter = Router();

router.use(healthRouter);
router.use(brandingRouter);
router.use("/market", marketRouter);
router.use("/auth", authRouter);
router.use("/dashboard", dashboardRouter);
router.use("/investments", investmentsRouter);
router.use("/trades", tradesRouter);
router.use("/algo-strategies", algoStrategiesRouter);
router.use("/copy-traders", copyTradingRouter);
router.use("/ea-strategies", eaStrategiesRouter);
router.use("/transactions", transactionsRouter);
router.use("/admin", adminRouter);
router.use("/admin/notifications", adminNotificationsRouter);
router.use("/super-admin", superAdminRouter);
router.use("/plans", plansRouter);
router.use("/kyc", kycRouter);
router.use("/referral", referralRouter);
router.use("/mt5-accounts", mt5Router);
router.use("/mt5-relay", mt5RelayRouter);
router.use("/tickets", ticketsRouter);
router.use("/notifications", notificationsRouter);
router.use("/wallet", walletRouter);
router.use("/manager", managerRouter);
router.use("/support-team", supportTeamRouter);
router.use("/support-team/mail", supportMailRouter);
router.use("/admin/mail", supportMailRouter);
router.use("/promoter", promoterRouter);
router.use("/auth/2fa", twoFactorRouter);
router.use("/roi", roiEngineRouter);
router.use("/audit-logs", auditLogsRouter);
router.use("/promo-codes", promoCodesRouter);
router.use("/agreements", agreementsRouter);
router.use("/payments", paymentsRouter);
router.use("/wallet-ledger", walletLedgerRouter);
router.use("/onboarding", onboardingRouter);
router.use("/uploads-secure", uploadsRouter);
router.use("/wallet/payment-accounts", paymentAccountsRouter);

export default router;
