import { DEFAULT_STAKING_PLANS } from "./ensureStakingSchema";

/** Demo investment plans — mirrors scripts/src/seed.ts catalog. */
const DEFAULT_INVESTMENT_PLAN_SEEDS = [
  {
    name: "Starter Plan",
    description: "Perfect for new investors. Low risk, steady returns.",
    minAmount: 500,
    maxAmount: 5000,
    roiPercent: 8.5,
    durationDays: 30,
    currency: "USD",
    category: "starter",
    totalInvestors: 1247,
  },
  {
    name: "Growth Plan",
    description: "Balanced portfolio for consistent wealth growth.",
    minAmount: 5000,
    maxAmount: 25000,
    roiPercent: 15.0,
    durationDays: 60,
    currency: "USD",
    category: "growth",
    totalInvestors: 834,
  },
  {
    name: "Premium Plan",
    description: "Advanced strategies for seasoned investors.",
    minAmount: 25000,
    maxAmount: 100000,
    roiPercent: 24.0,
    durationDays: 90,
    currency: "USD",
    category: "premium",
    totalInvestors: 312,
  },
  {
    name: "Elite Plan",
    description: "Exclusive hedge fund strategies. Maximum returns.",
    minAmount: 100000,
    maxAmount: 1000000,
    roiPercent: 36.0,
    durationDays: 180,
    currency: "USD",
    category: "elite",
    totalInvestors: 89,
  },
] as const;

export function getDefaultInvestmentPlans() {
  return DEFAULT_INVESTMENT_PLAN_SEEDS.map((p, i) => ({
    id: -(i + 1),
    name: p.name,
    description: p.description,
    minAmount: p.minAmount,
    maxAmount: p.maxAmount,
    roiPercent: p.roiPercent,
    durationDays: p.durationDays,
    currency: p.currency,
    isActive: true,
    totalInvestors: p.totalInvestors,
    category: p.category,
    planType: "monthly" as const,
    profitFrequency: "monthly" as const,
    capitalReturn: "yes" as const,
    autoRenewal: false,
    earlyWithdrawalPenalty: 0,
    features: [] as string[],
    maxInvestors: null as number | null,
    createdAt: null as string | null,
  }));
}

export function getDefaultStakingPlans() {
  return DEFAULT_STAKING_PLANS.map((p, i) => ({
    id: -(i + 1),
    name: p.name,
    description: p.description ?? null,
    planType: p.planType,
    currency: p.currency,
    minAmount: Number(p.minAmount),
    maxAmount: Number(p.maxAmount),
    aprPercent: Number(p.aprPercent),
    apyPercent: Number(p.apyPercent),
    roiPercent: Number(p.roiPercent),
    lockDurationDays: p.lockDurationDays,
    isFlexible: p.isFlexible ?? false,
    rewardFrequency: p.rewardFrequency,
    compoundEnabled: p.compoundEnabled ?? false,
    autoRenew: p.autoRenew ?? false,
    earlyWithdrawalPenalty: Number(p.earlyWithdrawalPenalty ?? 0),
    promotionalBonusPercent: 0,
    isActive: true,
    isFeatured: p.isFeatured ?? false,
    isPopular: p.isPopular ?? false,
    isRecommended: p.isRecommended ?? false,
    riskLevel: p.riskLevel ?? "medium",
    maxUsers: null as number | null,
    totalPoolLimit: null as number | null,
    totalStaked: 0,
    activeStakers: 0,
    themeColor: p.themeColor ?? "#f59e0b",
    iconKey: p.iconKey ?? "coins",
    sortOrder: p.sortOrder ?? i,
    promoEndsAt: null as string | null,
  }));
}
