import QRCode from "qrcode";
import { randomBytes } from "crypto";
import { getUploadRoot, getUploadUrl } from "../middlewares/upload";
import { deleteUploadObject, objectExists, putUploadObject } from "./objectStorage";
import { db, paymentGatewaysTable, userPaymentAccountsTable } from "@workspace/db";
import { eq } from "@workspace/db/orm";

export function buildUpiPayUri(
  upiId: string,
  payeeName: string,
  amount?: number,
  currency = "INR",
): string {
  const params = new URLSearchParams({
    pa: upiId.trim(),
    pn: payeeName.slice(0, 50),
    cu: currency,
    tn: "Kuber Quant Deposit",
  });
  if (amount && amount > 0) params.set("am", String(amount));
  return `upi://pay?${params.toString()}`;
}

export function buildDigitalRupeePayUri(
  digitalRupeeId: string,
  payeeName: string,
  amount?: number,
  currency = "INR",
): string {
  const params = new URLSearchParams({
    pa: digitalRupeeId.trim(),
    pn: payeeName.slice(0, 50),
    cu: currency,
    tn: "Kuber Quant Digital Rupee",
    mode: "CBDC",
  });
  if (amount && amount > 0) params.set("am", String(amount));
  return `cbdc://pay?${params.toString()}`;
}

export function isAutoGeneratedQrUrl(url?: string | null): boolean {
  if (!url) return false;
  return /\/qr_codes\/auto-(upi|digital-rupee|wallet)-/i.test(url);
}

export function parseQrCodesFilename(url: string): string | null {
  const match = url.match(/\/qr_codes\/([^/?#]+)/i);
  return match ? decodeURIComponent(match[1]) : null;
}

export async function autoQrFileExists(url: string | null | undefined): Promise<boolean> {
  if (!url?.trim()) return false;
  const filename = parseQrCodesFilename(url.trim());
  if (!filename) return false;
  return objectExists(getUploadRoot(), "qr_codes", filename);
}

export async function deleteAutoQrFile(url: string | null | undefined): Promise<void> {
  if (!url || !isAutoGeneratedQrUrl(url)) return;
  const filename = parseQrCodesFilename(url);
  if (!filename) return;
  await deleteUploadObject(getUploadRoot(), "qr_codes", filename).catch(() => {});
}

export async function generateQrPngFile(payload: string, prefix: "auto-upi" | "auto-digital-rupee" | "auto-wallet"): Promise<string> {
  const filename = `${prefix}-${Date.now()}-${randomBytes(4).toString("hex")}.png`;
  const buffer = await QRCode.toBuffer(payload, { width: 512, margin: 2, type: "png" });
  await putUploadObject(getUploadRoot(), "qr_codes", filename, buffer, "image/png");
  return getUploadUrl("qr_codes", filename);
}

export async function generateQrPngBuffer(payload: string): Promise<Buffer> {
  return QRCode.toBuffer(payload, { width: 512, margin: 2, type: "png" });
}

type GatewayQrInput = {
  type: string;
  name: string;
  upiId?: string | null;
  digitalRupeeId?: string | null;
  walletAddress?: string | null;
  qrCodeUrl?: string | null;
  identifierChanged?: boolean;
};

/** Returns stored QR URL — auto-generates PNG when UPI ID or wallet address is set. */
export async function resolveGatewayQrCode(input: GatewayQrInput): Promise<string | null> {
  const existing = input.qrCodeUrl?.trim() || null;
  const hasCustomUpload = !!existing && !isAutoGeneratedQrUrl(existing);

  if (hasCustomUpload && !input.identifierChanged) {
    return existing;
  }

  const autoStillValid = existing
    && isAutoGeneratedQrUrl(existing)
    && !input.identifierChanged
    && await autoQrFileExists(existing);

  if (autoStillValid) {
    return existing;
  }

  if (existing && isAutoGeneratedQrUrl(existing)) {
    await deleteAutoQrFile(existing);
  }

  if (input.type === "upi" && input.upiId?.trim()) {
    const uri = buildUpiPayUri(input.upiId.trim(), input.name || "UPI");
    return generateQrPngFile(uri, "auto-upi");
  }

  if (input.type === "digital_rupee" && input.digitalRupeeId?.trim()) {
    const uri = buildDigitalRupeePayUri(input.digitalRupeeId.trim(), input.name || "Digital Rupee");
    return generateQrPngFile(uri, "auto-digital-rupee");
  }

  if (input.type === "crypto" && input.walletAddress?.trim()) {
    return generateQrPngFile(input.walletAddress.trim(), "auto-wallet");
  }

  return hasCustomUpload ? existing : null;
}

type UserAccountQrInput = {
  accountType: string;
  label: string;
  upiId?: string | null;
  digitalRupeeId?: string | null;
  walletAddress?: string | null;
  upiQrUrl?: string | null;
  walletQrUrl?: string | null;
  identifierChanged?: boolean;
};

export async function resolveUserAccountQrUrls(input: UserAccountQrInput): Promise<{
  upiQrUrl?: string | null;
  walletQrUrl?: string | null;
}> {
  const result: { upiQrUrl?: string | null; walletQrUrl?: string | null } = {};

  if (input.accountType === "upi" && input.upiId?.trim()) {
    const existing = input.upiQrUrl?.trim() || null;
    const hasCustom = !!existing && !isAutoGeneratedQrUrl(existing);
    const autoValid = existing
      && isAutoGeneratedQrUrl(existing)
      && !input.identifierChanged
      && await autoQrFileExists(existing);

    if (hasCustom && !input.identifierChanged) {
      result.upiQrUrl = existing;
    } else if (autoValid) {
      result.upiQrUrl = existing;
    } else {
      if (existing && isAutoGeneratedQrUrl(existing)) {
        await deleteAutoQrFile(existing);
      }
      const uri = buildUpiPayUri(input.upiId.trim(), input.label || "UPI");
      result.upiQrUrl = await generateQrPngFile(uri, "auto-upi");
    }
  }

  if (input.accountType === "digital_rupee" && input.digitalRupeeId?.trim()) {
    const existing = input.upiQrUrl?.trim() || null;
    const hasCustom = !!existing && !isAutoGeneratedQrUrl(existing);
    const autoValid = existing
      && isAutoGeneratedQrUrl(existing)
      && !input.identifierChanged
      && await autoQrFileExists(existing);

    if (hasCustom && !input.identifierChanged) {
      result.upiQrUrl = existing;
    } else if (autoValid) {
      result.upiQrUrl = existing;
    } else {
      if (existing && isAutoGeneratedQrUrl(existing)) {
        await deleteAutoQrFile(existing);
      }
      const uri = buildDigitalRupeePayUri(input.digitalRupeeId.trim(), input.label || "Digital Rupee");
      result.upiQrUrl = await generateQrPngFile(uri, "auto-digital-rupee");
    }
  }

  if (input.accountType === "crypto" && input.walletAddress?.trim()) {
    const existing = input.walletQrUrl?.trim() || null;
    const hasCustom = !!existing && !isAutoGeneratedQrUrl(existing);
    const autoValid = existing
      && isAutoGeneratedQrUrl(existing)
      && !input.identifierChanged
      && await autoQrFileExists(existing);

    if (hasCustom && !input.identifierChanged) {
      result.walletQrUrl = existing;
    } else if (autoValid) {
      result.walletQrUrl = existing;
    } else {
      if (existing && isAutoGeneratedQrUrl(existing)) {
        await deleteAutoQrFile(existing);
      }
      result.walletQrUrl = await generateQrPngFile(input.walletAddress.trim(), "auto-wallet");
    }
  }

  return result;
}

type GatewayRow = typeof paymentGatewaysTable.$inferSelect;

/** Regenerate missing/stale auto QRs and persist updated URLs. */
export async function ensurePaymentGatewayQrs(gateways: GatewayRow[]): Promise<GatewayRow[]> {
  for (const gw of gateways) {
    const needsQr = (gw.type === "upi" && gw.upiId?.trim())
      || (gw.type === "digital_rupee" && gw.digitalRupeeId?.trim())
      || (gw.type === "crypto" && gw.walletAddress?.trim());
    if (!needsQr) continue;

    const qr = await resolveGatewayQrCode({
      type: gw.type,
      name: gw.name,
      upiId: gw.upiId,
      digitalRupeeId: gw.digitalRupeeId,
      walletAddress: gw.walletAddress,
      qrCodeUrl: gw.qrCodeUrl,
    });

    if (qr && qr !== gw.qrCodeUrl) {
      await db.update(paymentGatewaysTable)
        .set({ qrCodeUrl: qr, updatedAt: new Date() })
        .where(eq(paymentGatewaysTable.id, gw.id));
      gw.qrCodeUrl = qr;
    }
  }
  return gateways;
}

type UserAccountRow = typeof userPaymentAccountsTable.$inferSelect;

/** Regenerate missing/stale auto QRs for a user payout account and persist. */
export async function ensureUserPaymentAccountQr(account: UserAccountRow): Promise<UserAccountRow> {
  const autoQr = await resolveUserAccountQrUrls({
    accountType: account.accountType,
    label: account.label,
    upiId: account.upiId,
    digitalRupeeId: account.digitalRupeeId,
    walletAddress: account.walletAddress,
    upiQrUrl: account.upiQrUrl,
    walletQrUrl: account.walletQrUrl,
  });

  const updates: Partial<UserAccountRow> = {};
  if (autoQr.upiQrUrl !== undefined && autoQr.upiQrUrl !== account.upiQrUrl) {
    updates.upiQrUrl = autoQr.upiQrUrl;
  }
  if (autoQr.walletQrUrl !== undefined && autoQr.walletQrUrl !== account.walletQrUrl) {
    updates.walletQrUrl = autoQr.walletQrUrl;
  }

  if (Object.keys(updates).length === 0) return account;

  const [updated] = await db.update(userPaymentAccountsTable)
    .set({ ...updates, updatedAt: new Date() })
    .where(eq(userPaymentAccountsTable.id, account.id))
    .returning();

  return updated || account;
}

export async function ensureAllPaymentGatewayQrsInDb(): Promise<number> {
  const gateways = await db.select().from(paymentGatewaysTable);
  const before = gateways.map(g => g.qrCodeUrl);
  await ensurePaymentGatewayQrs(gateways);
  return gateways.filter((g, i) => g.qrCodeUrl !== before[i]).length;
}
